DROP TABLE IF EXISTS `car_rental_bookings`;
CREATE TABLE IF NOT EXISTS `car_rental_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` int(10) unsigned DEFAULT NULL,
  `type_id` int(10) unsigned DEFAULT NULL,
  `car_id` int(10) unsigned DEFAULT NULL,
  `pickup_id` int(10) unsigned DEFAULT NULL COMMENT 'Location ID',
  `return_id` int(10) unsigned DEFAULT NULL COMMENT 'Location ID',
  `from` datetime DEFAULT NULL,
  `to` datetime DEFAULT NULL,
  `total` decimal(9,2) unsigned DEFAULT NULL,
  `deposit` decimal(9,2) unsigned DEFAULT NULL,
  `tax` decimal(9,2) unsigned DEFAULT NULL,
  `payment_method` enum('paypal','authorize','creditcard') DEFAULT NULL,
  `status` enum('confirmed','cancelled','pending') DEFAULT 'pending',
  `txn_id` varchar(255) DEFAULT NULL,
  `processed_on` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `c_title` varchar(255) DEFAULT NULL,
  `c_fname` varchar(255) DEFAULT NULL,
  `c_lname` varchar(255) DEFAULT NULL,
  `c_phone` varchar(255) DEFAULT NULL,
  `c_email` varchar(255) DEFAULT NULL,
  `c_company` varchar(255) DEFAULT NULL,
  `c_address_1` varchar(255) DEFAULT NULL,
  `c_address_2` varchar(255) DEFAULT NULL,
  `c_address_3` varchar(255) DEFAULT NULL,
  `c_city` varchar(255) DEFAULT NULL,
  `c_state` varchar(255) DEFAULT NULL,
  `c_zip` varchar(255) DEFAULT NULL,
  `c_country` int(10) unsigned DEFAULT NULL,
  `cc_type` varchar(255) DEFAULT NULL,
  `cc_num` varchar(255) DEFAULT NULL,
  `cc_exp` varchar(255) DEFAULT NULL,
  `cc_code` varchar(255) DEFAULT NULL,
  `locale_id` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `car_id` (`car_id`),
  KEY `type_id` (`type_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_bookings_extras`;
CREATE TABLE IF NOT EXISTS `car_rental_bookings_extras` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned DEFAULT NULL,
  `extra_id` int(10) unsigned DEFAULT NULL,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `booking_id` (`booking_id`,`extra_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_cars`;
CREATE TABLE IF NOT EXISTS `car_rental_cars` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `location_id` int(10) unsigned DEFAULT NULL,
  `registration_number` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `registration_number` (`registration_number`),
  KEY `location_id` (`location_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_cars_types`;
CREATE TABLE IF NOT EXISTS `car_rental_cars_types` (
  `car_id` int(10) unsigned NOT NULL,
  `type_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`car_id`,`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_countries`;
CREATE TABLE IF NOT EXISTS `car_rental_countries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_title` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_extras`;
CREATE TABLE IF NOT EXISTS `car_rental_extras` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `per` enum('booking','day') DEFAULT NULL,
  `count` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_i18n`;
CREATE TABLE IF NOT EXISTS `car_rental_i18n` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `foreign_id` int(10) unsigned DEFAULT NULL,
  `model` varchar(70) DEFAULT NULL,
  `locale` tinyint(3) unsigned DEFAULT NULL,
  `field` varchar(100) DEFAULT NULL,
  `content` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `foreign_id` (`foreign_id`,`model`,`locale`,`field`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_locations`;
CREATE TABLE IF NOT EXISTS `car_rental_locations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_id` int(10) unsigned DEFAULT NULL,
  `zip` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `lat` varchar(255) DEFAULT NULL,
  `lng` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country_id` (`country_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_options`;
CREATE TABLE IF NOT EXISTS `car_rental_options` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL DEFAULT '',
  `tab_id` tinyint(3) unsigned DEFAULT NULL,
  `group` enum('borders','colors','fonts','sizes') DEFAULT NULL,
  `value` text,
  `description` text,
  `label` text,
  `type` enum('string','text','int','float','enum','color') NOT NULL DEFAULT 'string',
  `order` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`),
  KEY `tab_id` (`tab_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_prices`;
CREATE TABLE IF NOT EXISTS `car_rental_prices` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type_id` int(10) unsigned DEFAULT NULL,
  `date_from` datetime NOT NULL,
  `date_to` datetime NOT NULL,
  `time_from` time DEFAULT NULL,
  `time_to` time DEFAULT NULL,
  `length_1_4` smallint(5) unsigned DEFAULT NULL,
  `length_1_2` smallint(5) unsigned DEFAULT NULL,
  `price_1_4` decimal(7,2) unsigned DEFAULT NULL,
  `price_1_2` decimal(7,2) unsigned DEFAULT NULL,
  `price` decimal(7,2) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `type_id` (`type_id`,`date_from`,`date_to`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_roles`;
CREATE TABLE IF NOT EXISTS `car_rental_roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_types`;
CREATE TABLE IF NOT EXISTS `car_rental_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `passengers` smallint(5) unsigned DEFAULT NULL,
  `luggages` tinyint(3) unsigned DEFAULT NULL,
  `doors` tinyint(3) unsigned DEFAULT NULL,
  `size` enum('small','medium','large') DEFAULT NULL,
  `transmission` enum('manual','automatic','semi-automatic') DEFAULT NULL,
  `thumb_path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_types_extras`;
CREATE TABLE IF NOT EXISTS `car_rental_types_extras` (
  `type_id` int(10) unsigned NOT NULL,
  `extra_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`type_id`,`extra_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `car_rental_users`;
CREATE TABLE IF NOT EXISTS `car_rental_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(10) unsigned NOT NULL,
  `username` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(40) NOT NULL DEFAULT '',
  `created` datetime NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `role_id` (`role_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `car_rental_countries` (`id`, `country_title`, `status`) VALUES
(1, 'Afghanistan', 'T'),
(2, 'Albania', 'T'),
(3, 'Algeria', 'T'),
(4, 'American Samoa', 'T'),
(5, 'Andorra', 'T'),
(6, 'Angola', 'T'),
(7, 'Anguilla', 'T'),
(8, 'Antarctica', 'T'),
(9, 'Antigua and Barbuda', 'T'),
(10, 'Argentina', 'T'),
(11, 'Armenia', 'T'),
(12, 'Arctic Ocean', 'T'),
(13, 'Aruba', 'T'),
(14, 'Ashmore and Cartier Islands', 'T'),
(15, 'Atlantic Ocean', 'T'),
(16, 'Australia', 'T'),
(17, 'Austria', 'T'),
(18, 'Azerbaijan', 'T'),
(19, 'Bahamas', 'T'),
(20, 'Bahrain', 'T'),
(21, 'Baker Island', 'T'),
(22, 'Bangladesh', 'T'),
(23, 'Barbados', 'T'),
(24, 'Bassas da India', 'T'),
(25, 'Belarus', 'T'),
(26, 'Belgium', 'T'),
(27, 'Belize', 'T'),
(28, 'Benin', 'T'),
(29, 'Bermuda', 'T'),
(30, 'Bhutan', 'T'),
(31, 'Bolivia', 'T'),
(32, 'Borneo', 'T'),
(33, 'Bosnia and Herzegovina', 'T'),
(34, 'Botswana', 'T'),
(35, 'Bouvet Island', 'T'),
(36, 'Brazil', 'T'),
(37, 'British Virgin Islands', 'T'),
(38, 'Brunei', 'T'),
(39, 'Bulgaria', 'T'),
(40, 'Burkina Faso', 'T'),
(41, 'Burundi', 'T'),
(42, 'Cambodia', 'T'),
(43, 'Cameroon', 'T'),
(44, 'Canada', 'T'),
(45, 'Cape Verde', 'T'),
(46, 'Cayman Islands', 'T'),
(47, 'Central African Republic', 'T'),
(48, 'Chad', 'T'),
(49, 'Chile', 'T'),
(50, 'China', 'T'),
(51, 'Christmas Island', 'T'),
(52, 'Clipperton Island', 'T'),
(53, 'Cocos Islands', 'T'),
(54, 'Colombia', 'T'),
(55, 'Comoros', 'T'),
(56, 'Cook Islands', 'T'),
(57, 'Coral Sea Islands', 'T'),
(58, 'Costa Rica', 'T'),
(59, 'Cote d''Ivoire', 'T'),
(60, 'Croatia', 'T'),
(61, 'Cuba', 'T'),
(62, 'Cyprus', 'T'),
(63, 'Czech Republic', 'T'),
(64, 'Denmark', 'T'),
(65, 'Democratic Republic of the Congo', 'T'),
(66, 'Djibouti', 'T'),
(67, 'Dominica', 'T'),
(68, 'Dominican Republic', 'T'),
(69, 'East Timor', 'T'),
(70, 'Ecuador', 'T'),
(71, 'Egypt', 'T'),
(72, 'El Salvador', 'T'),
(73, 'Equatorial Guinea', 'T'),
(74, 'Eritrea', 'T'),
(75, 'Estonia', 'T'),
(76, 'Ethiopia', 'T'),
(77, 'Europa Island', 'T'),
(78, 'Falkland Islands (Islas Malvinas)', 'T'),
(79, 'Faroe Islands', 'T'),
(80, 'Fiji', 'T'),
(81, 'Finland', 'T'),
(82, 'France', 'T'),
(83, 'French Guiana', 'T'),
(84, 'French Polynesia', 'T'),
(85, 'French Southern and Antarctic Lands', 'T'),
(86, 'Gabon', 'T'),
(87, 'Gambia', 'T'),
(88, 'Gaza Strip', 'T'),
(89, 'Georgia', 'T'),
(90, 'Germany', 'T'),
(91, 'Ghana', 'T'),
(92, 'Gibraltar', 'T'),
(93, 'Glorioso Islands', 'T'),
(94, 'Greece', 'T'),
(95, 'Greenland', 'T'),
(96, 'Grenada', 'T'),
(97, 'Guadeloupe', 'T'),
(98, 'Guam', 'T'),
(99, 'Guatemala', 'T'),
(100, 'Guernsey', 'T'),
(101, 'Guinea', 'T'),
(102, 'Guinea-Bissau', 'T'),
(103, 'Guyana', 'T'),
(104, 'Haiti', 'T'),
(105, 'Heard Island and McDonald Islands', 'T'),
(106, 'Honduras', 'T'),
(107, 'Hong Kong', 'T'),
(108, 'Howland Island', 'T'),
(109, 'Hungary', 'T'),
(110, 'Iceland', 'T'),
(111, 'India', 'T'),
(112, 'Indian Ocean', 'T'),
(113, 'Indonesia', 'T'),
(114, 'Iran', 'T'),
(115, 'Iraq', 'T'),
(116, 'Ireland', 'T'),
(117, 'Isle of Man', 'T'),
(118, 'Israel', 'T'),
(119, 'Italy', 'T'),
(120, 'Jamaica', 'T'),
(121, 'Jan Mayen', 'T'),
(122, 'Japan', 'T'),
(123, 'Jarvis Island', 'T'),
(124, 'Jersey', 'T'),
(125, 'Johnston Atoll', 'T'),
(126, 'Jordan', 'T'),
(127, 'Juan de Nova Island', 'T'),
(128, 'Kazakhstan', 'T'),
(129, 'Kenya', 'T'),
(130, 'Kingman Reef', 'T'),
(131, 'Kiribati', 'T'),
(132, 'Kerguelen Archipelago', 'T'),
(133, 'Kosovo', 'T'),
(134, 'Kuwait', 'T'),
(135, 'Kyrgyzstan', 'T'),
(136, 'Laos', 'T'),
(137, 'Latvia', 'T'),
(138, 'Lebanon', 'T'),
(139, 'Lesotho', 'T'),
(140, 'Liberia', 'T'),
(141, 'Libya', 'T'),
(142, 'Liechtenstein', 'T'),
(143, 'Lithuania', 'T'),
(144, 'Luxembourg', 'T'),
(145, 'Macau', 'T'),
(146, 'Macedonia', 'T'),
(147, 'Madagascar', 'T'),
(148, 'Malawi', 'T'),
(149, 'Malaysia', 'T'),
(150, 'Maldives', 'T'),
(151, 'Mali', 'T'),
(152, 'Malta', 'T'),
(153, 'Marshall Islands', 'T'),
(154, 'Martinique', 'T'),
(155, 'Mauritania', 'T'),
(156, 'Mauritius', 'T'),
(157, 'Mayotte', 'T'),
(158, 'Mediterranean Sea', 'T'),
(159, 'Mexico', 'T'),
(160, 'Micronesia', 'T'),
(161, 'Midway Islands', 'T'),
(162, 'Moldova', 'T'),
(163, 'Monaco', 'T'),
(164, 'Mongolia', 'T'),
(165, 'Montenegro', 'T'),
(166, 'Montserrat', 'T'),
(167, 'Morocco', 'T'),
(168, 'Mozambique', 'T'),
(169, 'Myanmar', 'T'),
(170, 'Namibia', 'T'),
(171, 'Nauru', 'T'),
(172, 'Navassa Island', 'T'),
(173, 'Nepal', 'T'),
(174, 'Netherlands', 'T'),
(175, 'Netherlands Antilles', 'T'),
(176, 'New Caledonia', 'T'),
(177, 'New Zealand', 'T'),
(178, 'Nicaragua', 'T'),
(179, 'Niger', 'T'),
(180, 'Nigeria', 'T'),
(181, 'Niue', 'T'),
(182, 'Norfolk Island', 'T'),
(183, 'North Korea', 'T'),
(184, 'North Sea', 'T'),
(185, 'Northern Mariana Islands', 'T'),
(186, 'Norway', 'T'),
(187, 'Oman', 'T'),
(188, 'Pacific Ocean', 'T'),
(189, 'Pakistan', 'T'),
(190, 'Palau', 'T'),
(191, 'Palmyra Atoll', 'T'),
(192, 'Panama', 'T'),
(193, 'Papua New Guinea', 'T'),
(194, 'Paracel Islands', 'T'),
(195, 'Paraguay', 'T'),
(196, 'Peru', 'T'),
(197, 'Philippines', 'T'),
(198, 'Pitcairn Islands', 'T'),
(199, 'Poland', 'T'),
(200, 'Portugal', 'T'),
(201, 'Puerto Rico', 'T'),
(202, 'Qatar', 'T'),
(203, 'Reunion', 'T'),
(204, 'Republic of the Congo', 'T'),
(205, 'Romania', 'T'),
(206, 'Ross Sea', 'T'),
(207, 'Russia', 'T'),
(208, 'Rwanda', 'T'),
(209, 'Saint Helena', 'T'),
(210, 'Saint Kitts and Nevis', 'T'),
(211, 'Saint Lucia', 'T'),
(212, 'Saint Pierre and Miquelon', 'T'),
(213, 'Saint Vincent and the Grenadines', 'T'),
(214, 'Samoa', 'T'),
(215, 'San Marino', 'T'),
(216, 'Sao Tome and Principe', 'T'),
(217, 'Saudi Arabia', 'T'),
(218, 'Senegal', 'T'),
(219, 'Serbia', 'T'),
(220, 'Seychelles', 'T'),
(221, 'Sierra Leone', 'T'),
(222, 'Singapore', 'T'),
(223, 'Slovakia', 'T'),
(224, 'Slovenia', 'T'),
(225, 'Solomon Islands', 'T'),
(226, 'Somalia', 'T'),
(227, 'South Africa', 'T'),
(228, 'South Georgia and the South Sandwich Islands', 'T'),
(229, 'South Korea', 'T'),
(230, 'Southern Ocean', 'T'),
(231, 'Spain', 'T'),
(232, 'Spratly Islands', 'T'),
(233, 'Sri Lanka', 'T'),
(234, 'Sudan', 'T'),
(235, 'Suriname', 'T'),
(236, 'Svalbard', 'T'),
(237, 'Swaziland', 'T'),
(238, 'Sweden', 'T'),
(239, 'Switzerland', 'T'),
(240, 'Syria', 'T'),
(241, 'Taiwan', 'T'),
(242, 'Tajikistan', 'T'),
(243, 'Tanzania', 'T'),
(244, 'Tasman Sea', 'T'),
(245, 'Thailand', 'T'),
(246, 'Togo', 'T'),
(247, 'Tokelau', 'T'),
(248, 'Tonga', 'T'),
(249, 'Trinidad and Tobago', 'T'),
(250, 'Tromelin Island', 'T'),
(251, 'Tunisia', 'T'),
(252, 'Turkey', 'T'),
(253, 'Turkmenistan', 'T'),
(254, 'Turks and Caicos Islands', 'T'),
(255, 'Tuvalu', 'T'),
(256, 'Uganda', 'T'),
(257, 'Ukraine', 'T'),
(258, 'United Arab Emirates', 'T'),
(259, 'United Kingdom', 'T'),
(260, 'USA', 'T'),
(261, 'Uruguay', 'T'),
(262, 'Uzbekistan', 'T'),
(263, 'Vanuatu', 'T'),
(264, 'Venezuela', 'T'),
(265, 'Viet Nam', 'T'),
(266, 'Virgin Islands', 'T'),
(267, 'Wake Island', 'T'),
(268, 'Wallis and Futuna', 'T'),
(269, 'West Bank', 'T'),
(270, 'Western Sahara', 'T'),
(271, 'Yemen', 'T'),
(272, 'Zambia', 'T'),
(273, 'Zimbabwe', 'T');

INSERT INTO `car_rental_options` (`id`, `key`, `tab_id`, `group`, `value`, `description`, `label`, `type`, `order`) VALUES
(NULL, 'db_version', 99, NULL, '1.1.2', 'Database version', NULL, 'string', NULL),
(NULL, 'currency', 1, NULL, 'USD|GBP|EUR::USD', 'Currency', NULL, 'enum', 1),
(NULL, 'bf_include_address_1', 5, NULL, '1|2|3::3', 'Address Line 1<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 7),
(NULL, 'bf_include_city', 5, NULL, '1|2|3::3', 'City<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 10),
(NULL, 'bf_include_country', 5, NULL, '1|2|3::3', 'Country<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 13),
(NULL, 'bf_include_email', 5, NULL, '1|2|3::3', 'E-Mail address<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 5),
(NULL, 'bf_include_fname', 5, NULL, '1|2|3::3', 'First Name<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 2),
(NULL, 'bf_include_phone', 5, NULL, '1|2|3::3', 'Phone<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 4),
(NULL, 'bf_include_state', 5, NULL, '1|2|3::3', 'State<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 11),
(NULL, 'bf_include_zip', 5, NULL, '1|2|3::3', 'Zip<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 12),
(NULL, 'email_address', 4, NULL, 'info@domain.com', 'Notification email address', NULL, 'string', 1),
(NULL, 'email_confirmation', 4, NULL, '1|2|3::2', 'Send confirmation email<br />\r\n<span style="font-size: 0.9em">select if and when confirmation email should be sent to clients after they make a booking</span>', 'None|After booking form|After payment', 'enum', 2),
(NULL, 'email_confirmation_message', 4, NULL, 'You''ve just made a booking.\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress 1: {Address1}\r\nAddress 2: {Address2}\r\nAddress 3: {Address3}\r\nCompany: {Company}\r\n\r\nBooking details:\r\nDate/Time From: {DtFrom}\r\nDate/Time To: {DtTo}\r\nType: {Type}\r\nPickup: {PickupLocation}\r\nReturn: {ReturnLocation}\r\nExtras: {Extras}\r\nBooking ID: {BookingID}\r\nUnique ID: {UniqueID}\r\nDeposit: {Deposit}\r\nTotal: {Total}\r\nTax: {Tax}\r\n\r\nIf you want to cancel your booking follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.', 'Confirmation email<br />\r\n<u>Available Tokens:</u><br />\r\n{Title}<br />\r\n{FirstName}<br />\r\n{LastName}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address1}<br />\r\n{Address2}<br />\r\n{Address3}<br />\r\n{Company}<br />\r\n{DtFrom}<br />\r\n{DtTo}<br />\r\n{PickupLocation}<br />\r\n{ReturnLocation}<br />\r\n{Type}<br />\r\n{Extras}<br />\r\n{BookingID}<br />\r\n{UniqueID}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 4),
(NULL, 'email_confirmation_subject', 4, NULL, 'Confirmation message', 'Confirmation email subject', NULL, 'string', 3),
(NULL, 'email_payment', 4, NULL, '1|3::1', 'Send payment confirmation email<br />\r\n<span style="font-size: 0.9em">select if and when confirmation email should be sent to clients after they make a payment for their booking</span>', 'None|After payment', 'enum', 5),
(NULL, 'email_payment_message', 4, NULL, 'You''ve just made a booking.\r\n\r\nPersonal details:\r\nTitle: {Title}\r\nFirst Name: {FirstName}\r\nLast Name: {LastName}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress 1: {Address1}\r\nAddress 2: {Address2}\r\nAddress 3: {Address3}\r\nCompany: {Company}\r\n\r\nBooking details:\r\nDate/Time From: {DtFrom}\r\nDate/Time To: {DtTo}\r\nType: {Type}\r\nPickup: {PickupLocation}\r\nReturn: {ReturnLocation}\r\nExtras: {Extras}\r\nBooking ID: {BookingID}\r\nUnique ID: {UniqueID}\r\nDeposit: {Deposit}\r\nTotal: {Total}\r\nTax: {Tax}\r\n\r\nIf you want to cancel your booking follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.', 'Confirmation email<br />\r\n<u>Available Tokens:</u><br />\r\n{Title}<br />\r\n{FirstName}<br />\r\n{LastName}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address1}<br />\r\n{Address2}<br />\r\n{Address3}<br />\r\n{Company}<br />\r\n{DtFrom}<br />\r\n{DtTo}<br />\r\n{PickupLocation}<br />\r\n{ReturnLocation}<br />\r\n{Type}<br />\r\n{Extras}<br />\r\n{BookingID}<br />\r\n{UniqueID}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 7),
(NULL, 'email_payment_subject', 4, NULL, 'Payment message', 'Payment email subject', NULL, 'string', 6),
(NULL, 'terms', 6, NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu ipsum consectetur arcu commodo egestas nec eu ante. Aenean nec enim lorem. Proin accumsan luctus luctus. Vivamus pulvinar mollis orci, id convallis eros ultricies vel. Nullam adipiscing, risus non pellentesque aliquam, nibh ligula dictum justo, quis commodo nisi dolor ut nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ante leo, ultricies quis gravida id, vestibulum nec risus. Mauris adipiscing vestibulum nibh non ullamcorper. Suspendisse justo turpis, mattis a cursus ac, vulputate quis metus. Fusce vestibulum faucibus dignissim. Aliquam fermentum mauris felis, a ultrices sem.\r\n\r\nSuspendisse porttitor, odio eget eleifend aliquet, nibh urna placerat lacus, a rhoncus metus metus et lectus. Fusce convallis nunc dignissim magna condimentum sed lobortis nibh faucibus. Vivamus gravida libero et elit sagittis vel dignissim erat euismod. Nullam quam mi, mollis non feugiat et, facilisis eget sapien. Pellentesque sapien enim, dictum sit amet tincidunt eget, mollis et velit. Aenean scelerisque sem quis eros imperdiet et interdum nunc pellentesque. Morbi consectetur mauris sed sapien tristique eget malesuada tellus suscipit. Praesent aliquam hendrerit purus et vestibulum. Pellentesque dictum lorem velit, id semper tortor. ', 'Terms &amp; Conditions', NULL, 'text', 1),
(NULL, 'booking_status', 3, NULL, 'confirmed|pending|cancelled::pending', 'Default booking status<br />\r\n<span style="font-size: 0.9em">set the default status for each booking after it is made</span>', NULL, 'enum', 5),
(NULL, 'deposit_percent', 3, NULL, '10', 'Deposit payment <br />\r\n<span style="font-size: 0.9em">set amount of the booking amount to be paid as a deposit.</span>', NULL, 'int', 2),
(NULL, 'payment_authorize_key', 3, NULL, '', 'Authorize.net transaction key', NULL, 'string', 34),
(NULL, 'payment_authorize_mid', 3, NULL, '', 'Authorize.net merchant ID', NULL, 'string', 35),
(NULL, 'payment_disable', 3, NULL, 'No|Yes::No', 'Disable payments<br /><span style="font-size: 0.9em">to disable payments and only accept bookings, set this to "Yes"</span>', NULL, 'enum', 30),
(NULL, 'payment_enable_authorize', 3, NULL, 'Yes|No::Yes', 'Allow Authorize.net payments', NULL, 'enum', 33),
(NULL, 'payment_enable_creditcard', 3, NULL, 'Yes|No::Yes', 'Allow payments with Credit cards', NULL, 'enum', 38),
(NULL, 'payment_enable_paypal', 3, NULL, 'Yes|No::Yes', 'Allow PayPal payments', NULL, 'enum', 31),
(NULL, 'payment_status', 3, NULL, 'confirmed|pending|cancelled::confirmed', 'Default booking status after payment<br />\r\n<span style="font-size: 0.9em">set the default status for each booking after payment is made for it</span>', NULL, 'enum', 6),
(NULL, 'paypal_address', 3, NULL, 'paypal@domain.com', 'PayPal business email address', NULL, 'string', 32),
(NULL, 'tax', 3, NULL, '1', 'Tax payment %<br />\r\n<span style="font-size: 0.9em">set % for tax that clients pay</span>', NULL, 'float', 3),
(NULL, 'thank_you_page', 3, NULL, 'http://www.phpjabbers.com', '"Thank you" page location<br />\r\n<span style="font-size: 0.9em">this is the page where people will be redirected after paying</span>', NULL, 'string', 7),
(NULL, 'datetime_format', 1, NULL, 'd.m.Y, H:i|d.m.Y, H:i:s|m.d.Y, H:i|m.d.Y, H:i:s|Y.m.d, H:i|Y.m.d, H:i:s|j.n.Y, H:i|j.n.Y, H:i:s|n.j.Y, H:i|n.j.Y, H:i:s|Y.n.j, H:i|Y.n.j, H:i:s|d/m/Y, H:i|d/m/Y, H:i:s|m/d/Y, H:i|m/d/Y, H:i:s|Y/m/d, H:i|Y/m/d, H:i:s|j/n/Y, H:i|j/n/Y, H:i:s|n/j/Y, H:i|n/j/Y, H:i:s|Y/n/j, H:i|Y/n/j, H:i:s|d-m-Y, H:i|d-m-Y, H:i:s|m-d-Y, H:i|m-d-Y, H:i:s|Y-m-d, H:i|Y-m-d, H:i:s|j-n-Y, H:i|j-n-Y, H:i:s|n-j-Y, H:i|n-j-Y, H:i:s|Y-n-j, H:i|Y-n-j, H:i:s::j/n/Y, H:i', 'Date/Time format', 'd.m.Y, H:i (25.09.2010, 09:51)|d.m.Y, H:i:s (25.09.2010, 09:51:47)|m.d.Y, H:i (09.25.2010, 09:51)|m.d.Y, H:i:s (09.25.2010, 09:51:47)|Y.m.d, H:i (2010.09.25, 09:51)|Y.m.d, H:i:s (2010.09.25, 09:51:47)|j.n.Y, H:i (25.9.2010, 09:51)|j.n.Y, H:i:s (25.9.2010, 09:51:47)|n.j.Y, H:i (9.25.2010, 09:51)|n.j.Y, H:i:s (9.25.2010, 09:51:47)|Y.n.j, H:i (2010.9.25, 09:51)|Y.n.j, H:i:s (2010.9.25, 09:51:47)|d/m/Y, H:i (25/09/2010, 09:51)|d/m/Y, H:i:s (25/09/2010, 09:51:47)|m/d/Y, H:i (09/25/2010, 09:51)|m/d/Y, H:i:s (09/25/2010, 09:51:47)|Y/m/d, H:i (2010/09/25, 09:51)|Y/m/d, H:i:s (2010/09/25, 09:51:47)|j/n/Y, H:i (25/9/2010, 09:51)|j/n/Y, H:i:s (25/9/2010, 09:51:47)|n/j/Y, H:i (9/25/2010, 09:51)|n/j/Y, H:i:s (9/25/2010, 09:51:47)|Y/n/j, H:i (2010/9/25, 09:51)|Y/n/j, H:i:s (2010/9/25, 09:51:47)|d-m-Y, H:i (25-09-2010, 09:51)|d-m-Y, H:i:s (25-09-2010, 09:51:47)|m-d-Y, H:i (09-25-2010, 09:51)|m-d-Y, H:i:s (09-25-2010, 09:51:47)|Y-m-d, H:i (2010-09-25, 09:51)|Y-m-d, H:i:s (2010-09-25, 09:51:47)|j-n-Y, H:i (25-9-2010, 09:51)|j-n-Y, H:i:s (25-9-2010, 09:51:47)|n-j-Y, H:i (9-25-2010, 09:51)|n-j-Y, H:i:s (9-25-2010, 09:51:47)|Y-n-j, H:i (2010-9-25, 09:51)|Y-n-j, H:i:s (2010-9-25, 09:51:47)', 'enum', 3),
(NULL, 'date_format', 1, NULL, 'd.m.Y|m.d.Y|Y.m.d|j.n.Y|n.j.Y|Y.n.j|d/m/Y|m/d/Y|Y/m/d|j/n/Y|n/j/Y|Y/n/j|d-m-Y|m-d-Y|Y-m-d|j-n-Y|n-j-Y|Y-n-j::j/n/Y', 'Date format', 'd.m.Y (25.09.2010)|m.d.Y (09.25.2010)|Y.m.d (2010.09.25)|j.n.Y (25.9.2010)|n.j.Y (9.25.2010)|Y.n.j (2010.9.25)|d/m/Y (25/09/2010)|m/d/Y (09/25/2010)|Y/m/d (2010/09/25)|j/n/Y (25/9/2010)|n/j/Y (9/25/2010)|Y/n/j (2010/9/25)|d-m-Y (25-09-2010)|m-d-Y (09-25-2010)|Y-m-d (2010-09-25)|j-n-Y (25-9-2010)|n-j-Y (9-25-2010)|Y-n-j (2010-9-25)', 'enum', 2),
(NULL, 'bf_include_lname', 5, NULL, '1|2|3::3', 'Last Name<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 3),
(NULL, 'bf_include_address_2', 5, NULL, '1|2|3::2', 'Address Line 2<br />\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 8),
(NULL, 'bf_include_address_3', 5, NULL, '1|2|3::2', 'Address Line 3<br />\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 9),
(NULL, 'bf_include_company', 5, NULL, '1|2|3::2', 'Company<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 6),
(NULL, 'bf_include_title', 5, NULL, '1|2|3::3', 'Title<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 1),
(NULL, 'timezone', 1, NULL, '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'Timezone<br />\r\n<span style="font-size: 0.9em">select your time zone so booking interval can be limited based on your time zone</span>', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', 4);

INSERT INTO `car_rental_roles` (`id`, `role`, `status`) VALUES
(1, 'admin', 'T'),
(2, 'owner', 'T');